# -*- coding: utf-8 -*-
"""HW6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19mSNzY-YDXIage-HcW21W4kXt255nB2B
"""

print("github")